#!/usr/bin/env python
import sys
import linksdb.database


def main(args):

    if len(args) < 2:
        print('Missing command')
        return 1

    command = args[1]

    if command == 'create_db':
        linksdb.database.create()

    else:
        print('Unknown command {}'.format(command))
        return 1

    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
